# Generated by Django 2.2 on 2019-07-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_name',
            field=models.CharField(default='Paper', max_length=100),
            preserve_default=False,
        ),
    ]
