# Generated by Django 2.2.2 on 2019-07-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0003_auto_20190719_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_amount',
            new_name='client_total_amount',
        ),
    ]
