# Generated by Django 2.2.2 on 2019-07-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0005_auto_20190724_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='paper_no_of_sheets',
            new_name='paper_number_of_sheets',
        ),
    ]
