# Generated by Django 2.2.2 on 2019-07-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0006_auto_20190724_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchase_order_date_created_on',
            new_name='purchase_order_created_on',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchase_order_date_purchase_by',
            new_name='purchase_order_purchase_by',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchase_order_date_purchase_date',
            new_name='purchase_order_purchase_date',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchase_order_date_updated_on',
            new_name='purchase_order_updated_on',
        ),
    ]
