# Generated by Django 2.2.2 on 2019-07-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0008_auto_20190724_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_order_amount',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
