# Generated by Django 2.2.2 on 2019-07-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0010_purchaseorder_purchase_order_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_amount_due',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_total_amount',
        ),
    ]
