# Generated by Django 2.2.2 on 2019-07-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0011_auto_20190724_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_amount_due',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
    ]
