# Generated by Django 2.2.2 on 2019-07-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0012_process_process_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_amount_due',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_total_amount',
        ),
    ]
