# Generated by Django 2.2.2 on 2019-07-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0014_auto_20190725_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_gsm',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_size',
            field=models.CharField(max_length=300),
        ),
    ]
