# Generated by Django 2.2.2 on 2019-07-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0015_auto_20190725_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctp',
            old_name='ctp_no_of_plates',
            new_name='ctp_number_of_plates',
        ),
        migrations.RemoveField(
            model_name='ctp',
            name='ctp_size',
        ),
    ]
