# Generated by Django 2.2.2 on 2019-07-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0017_auto_20190729_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialprocess',
            name='specialprocess_size',
        ),
    ]
