# Generated by Django 2.2.2 on 2019-07-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0018_remove_specialprocess_specialprocess_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raiseuv',
            old_name='raiseuv_no_of_sheets',
            new_name='raiseuv_number_of_sheets',
        ),
    ]
