# Generated by Django 2.2.2 on 2019-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0019_auto_20190729_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseuv',
            name='raiseuv_impression',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
