# Generated by Django 2.2.2 on 2019-07-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0020_raiseuv_raiseuv_impression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiseuv',
            name='raiseuv_size',
        ),
    ]
