# Generated by Django 2.2.2 on 2019-07-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0021_remove_raiseuv_raiseuv_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varnish',
            old_name='varnish_no_of_sheets',
            new_name='varnish_number_of_sheets',
        ),
        migrations.RemoveField(
            model_name='varnish',
            name='varnish_size',
        ),
        migrations.AddField(
            model_name='varnish',
            name='varnish_impression',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
