# Generated by Django 2.2.2 on 2019-07-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0022_auto_20190730_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positive',
            name='positive_size',
        ),
        migrations.RemoveField(
            model_name='raiseuv',
            name='raiseuv_impression',
        ),
        migrations.RemoveField(
            model_name='varnish',
            name='varnish_impression',
        ),
    ]
