# Generated by Django 2.2.2 on 2019-07-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0024_auto_20190730_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lamination',
            old_name='lamination_no_of_sheets',
            new_name='lamination_number_of_sheets',
        ),
    ]
