# Generated by Django 2.2.2 on 2019-07-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0025_auto_20190730_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printing',
            old_name='printing_no_of_cols',
            new_name='printing_number_of_cols',
        ),
    ]
