# Generated by Django 2.2.2 on 2019-07-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0026_auto_20190730_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting',
            name='cutting_size',
        ),
    ]
