# Generated by Django 2.2.2 on 2019-07-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0029_auto_20190730_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folding',
            old_name='folding_no_of_folds',
            new_name='folding_number_of_folds',
        ),
    ]
