# Generated by Django 2.2.2 on 2019-07-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0030_auto_20190730_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creasing',
            name='creasing_size',
        ),
    ]
