# Generated by Django 2.2.2 on 2019-07-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0032_auto_20190730_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punch',
            name='punch_size',
        ),
    ]
