# Generated by Django 2.2.2 on 2019-07-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0034_auto_20190730_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourcol',
            name='fourcol_size',
        ),
    ]
